[package]
name = "qmbed-benchmark"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
nalgebra = "0.33"
num-bigint = "0.4"
qmbed = { git = "https://github.com/matrixlab-research/QMBED.git", rev = "58360f5ffed845d0f2fbd3649ad7588420edbc83" }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = "warn"
